### ISSUE TITLE
Opensimplex does not install, sad to say.

### ISSUE THREAD

**Issue by Torcelllo** [ClownsharkBatwing/RES4LYF#11]
Thanks for a brilliant repo. I appreciate the hard work gone into it.

![Opensimplex](https://github.com/user-attachments/assets/55d3124a-e744-4d09-a2dc-4b7c2ec801bf)

As I am not using a D: disc, it is all the more surprising to see this error

"D:\a\ComfyUI\python_embeded\python.exe"

Cannot get Opensimplex to install inside Standalone, as it says it is already installed (system install)

**Comment by ClownsharkBatwing** [comment]
Ended up removing Opensimplex by commenting out the code in noise_classes.py. It didn't seem to be a particularly useful noise mode and the install has been a persistent issue for many users. (Anyone that wants to use it still can by uncommenting it.)
